import { Icon } from "src/ui/components/Icon"
import FormatCard from "src/ui/components/Conversion/FormatCard"
import SideNav from "src/ui/components/Conversion/SideNav"
import faMagnifyingGlassSolid from 'src/ui/img/fa-magnifying-glass-solid-full.svg'
import { useDebouncedCallback } from 'use-debounce'

import './index.css'
import { useMemo, useState } from "preact/hooks"
import type { ConversionOption, ConversionOptionsMap } from "src/main.new"
import { Mode, ModeEnum } from "src/ui/ModeStore"
import {
    SelectedCategory,
    type FormatCategory, type CategoryEnum
} from "src/ui/FormatCategories"

interface FormatExplorerProps {
    categories: FormatCategory[]
    conversionOptions: ConversionOptionsMap
    onSelect?: (format: ConversionOption) => void
    debounceWaitMs?: number
}

type SearchIndex = Map<string, ConversionOption>

/**
 * Generates a search index which contains a `Map` of the flattened conversion option values as keys, and the actual {@linkcode ConversionOption} tuple as the value
 *
 * @param optionsMap The map of conversion options to process
 * @param advancedModeEnabled If Advanced Mode is disabled, omit extra conversion options
 */
function generateSearchIndex(optionsMap: ConversionOptionsMap, advancedModeEnabled: boolean): SearchIndex {
    const index: SearchIndex = new Map()
    for (const [file, handler] of optionsMap) {
        const keyStr = `${file.name}${file.format}${file.extension}${file.mime}${handler.name}`.toLowerCase()
        if (advancedModeEnabled) {
            index.set(keyStr, [file, handler])
        } else if (!index.has(keyStr)) {
            index.set(keyStr, [file, handler])
        }
    }
    return index
}

/**
     * Filters the given `SearchIndex` using `CategoryEnum`
     *
     * @param {SearchIndex} options The conversion options
     * @param {CategoryEnum} category The category to find
     * @returns The filtered search index
     */
function _filterByCategory(options: SearchIndex, category: CategoryEnum): SearchIndex {
    console.debug("Category filter:", category)
    if (category === 'all') return options

    const filteredFormats: SearchIndex = new Map()

    for (const [key, pair] of options) {
        if (
            typeof pair[0].category === "string"
            && pair[0].category === category
        ) filteredFormats.set(key, pair)
        if (typeof pair[0].category === "object") {
            for (const fileCat of pair[0].category) {
                if (fileCat === category) filteredFormats.set(key, pair)
            }
        }
    }

    console.debug("Category filter result:\n", filteredFormats)

    return filteredFormats
}

/**
 * Filters the given `SearchIndex` using the given search term by the `SearchIndex`'s search hash
 *
 * @param {SearchIndex} options The conversion options
 * @param {string} term The term to search for
 * @returns The filtered search index. If the term is an empty string, just sends back the `options` input
 */
function _filterByTerm(options: SearchIndex, term: string): SearchIndex {
    console.debug("Term filter:", term)
    if (term === "") return options

    const filteredFormats: SearchIndex = new Map()

    for (const [key, optionPair] of options) {
        if (key.includes(term))
            filteredFormats.set(key, optionPair)
    }

    console.debug("Term filter result:", filteredFormats)
    return filteredFormats
}

/**
 * Filter available cards according to the search term and where to search for it.
 *
 * Internally, it uses {@linkcode _filterByCategory} and {@linkcode _filterByTerm}
 * @param options The options to filter from
 * @param term The text to search for. Internally, it's lowercased
 */
function filterFormats(options: SearchIndex, term: string, category: CategoryEnum): SearchIndex {
    term = term.toLowerCase()
    return _filterByTerm(_filterByCategory(options, category), term)
    // return _filterByTerm(options, term)
}

export default function FormatExplorer({
    categories,
    conversionOptions,
    onSelect,
    debounceWaitMs = 250
}: FormatExplorerProps) {
    /**
     * Cached search index of conversion options
     *
     * See {@linkcode generateSearchIndex} for how it's done
     */
    const originalIndex = useMemo(
        () => generateSearchIndex(conversionOptions, Mode.value === ModeEnum.Advanced),
        [conversionOptions, Mode.value]
    )

    /** The search term */
    const [searchTerm, setSearchTerm] = useState("")

    /** The index of search results */
    const searchResultsIndex = useMemo(
        () => filterFormats(originalIndex, searchTerm, SelectedCategory.value),
        [searchTerm, SelectedCategory.value]
    )

    /**
     * Note the format ID here must correspond to the keys generated by {@linkcode generateSearchIndex}
     */
    const [selectedOptionId, setSelectedOptionId] =
        useState<string | null>(null)

    /**
     * Debounce handler for the search.
     *
     * If the input is empty, return all formats
     */
    const handleDebounceSearch = useDebouncedCallback((term) => {
        setSearchTerm(term)
    }, debounceWaitMs)

    /** Handles option selection by setting state and bubbling it up to the `onSelect` handler */
    const handleOptionSelection = (id: string, option: ConversionOption) => {
        setSelectedOptionId(id)
        onSelect?.(option)
    }

    return (
        <div className="format-explorer content-wrapper">
            <SideNav items={ categories } />

            {/* Center Browser */ }
            <section className="format-browser">
                <div className="search-container">
                    <div className="search-input-wrapper">
                        <Icon
                            src={ faMagnifyingGlassSolid }
                            className="icon"
                            size={ 16 }
                            color="var(--text-secondary)"
                        />
                        <input
                            type="text"
                            placeholder="Search for any format (e.g. PNG, MP4, WAV)..."
                            onInput={ (ev) => handleDebounceSearch(ev.currentTarget.value) }
                        />
                    </div>
                </div>

                <div className="format-list-container scroller">
                    <div className="list-header desktop-only">
                        {/* <h2>Common Formats</h2> */ }
                        <span>Showing { searchResultsIndex.size } formats</span>
                    </div>

                    <div className="format-grid">
                        {
                            Array.from(searchResultsIndex).map(([key, option]) => (
                                <FormatCard
                                    selected={ key === selectedOptionId }
                                    onSelect={ (key) => handleOptionSelection(key, option) }
                                    conversionOption={ option }
                                    id={ key }
                                    key={ key }
                                />
                            ))
                        }
                        {/* {
                            searchResultsIndex.map((option, i) => (
                                <FormatCard
                                    selected={ option[0] === selectedOptionId }
                                    onSelect={ (id) => handleFormatSelection(id, option) }
                                    formatType={ card }
                                    key={ card.id.concat(`-${i}`) }
                                    id={ card.id }
                                    handler={ card.handlerName }
                                />
                            ))
                        } */}
                    </div>
                </div>
            </section>
        </div>
    )
}
