import { Icon } from "../Icon";
import FormatCard from "./FormatCard";
import SideNav, { type FormatCategory } from "./SideNav";
import faMagnifyingGlassSolid from '../../img/fa-magnifying-glass-solid-full.svg';
import { useDebouncedCallback } from 'use-debounce';

import './FormatExplorer.css';
import { useMemo, useState } from "preact/hooks";
import type { ConversionOption, ConversionOptionsMap } from "src/main.new";
import { Mode, ModeEnum } from "src/ui/ModeStore";

interface FormatExplorerProps {
    categories: FormatCategory[];
    conversionOptions: ConversionOptionsMap
    onSelect?: (format: ConversionOption) => void;
    debounceWaitMs?: number;
}

type SearchIndex = Map<string, ConversionOption>

/**
 * Generates a search index which contains a `Map` of the flattened conversion option values as keys, and the actual {@linkcode ConversionOption} tuple as the value
 *
 * @param optionsMap The map of conversion options to process
 * @param advancedModeEnabled If Advanced Mode is disabled, omit extra conversion options
 */
function generateSearchIndex(optionsMap: ConversionOptionsMap, advancedModeEnabled: boolean): SearchIndex {
    const index: SearchIndex = new Map();
    for (const [file, handler] of optionsMap) {
        const keyStr = `${file.name}${file.format}${file.extension}${file.mime}${handler.name}`.toLowerCase();
        if (advancedModeEnabled || !index.has(keyStr)) {
            index.set(keyStr, [file, handler]);
        }
    }
    return index;
}

export default function FormatExplorer({
    categories,
    conversionOptions,
    onSelect,
    debounceWaitMs = 250
}: FormatExplorerProps) {
    /**
     * Cached search index of conversion options
     *
     * See {@linkcode generateSearchIndex} for how it's done
     */
    const originalIndex = useMemo(
        () => generateSearchIndex(conversionOptions, Mode.value === ModeEnum.Advanced),
        [conversionOptions, Mode.value]
    );

    /** The search term */
    const [searchTerm, setSearchTerm] = useState("");

    /** The index of search results */
    const searchResultsIndex = useMemo(
        () => !searchTerm
            ? originalIndex
            : filterFormats(originalIndex, searchTerm),
        [originalIndex, searchTerm]
    );

    /**
     * Note the format ID here must correspond to the keys generated by {@linkcode generateSearchIndex}
     */
    const [selectedOptionId, setSelectedOptionId] =
        useState<string | null>(null);

    /**
     * Filter available cards according to the search term and where to search for it
     * @param term The text to search for. Internally, it's lowercased
     */
    function filterFormats(options: SearchIndex, term: string): SearchIndex {
        const filteredFormats: SearchIndex = new Map();
        for (const [key, optionPair] of options) {
            if (key.includes(term.toLowerCase()))
                filteredFormats.set(key, optionPair);
        }
        return filteredFormats;
    }

    /**
     * Debounce handler for the search.
     *
     * If the input is empty, return all formats
     */
    const handleDebounceSearch = useDebouncedCallback((term) => {
        setSearchTerm(term);
    }, debounceWaitMs);

    /** Handles option selection by setting state and bubbling it up to the `onSelect` handler */
    const handleOptionSelection = (id: string, option: ConversionOption) => {
        setSelectedOptionId(id);
        onSelect?.(option);
    };

    return (
        <div className="format-explorer content-wrapper">
            <SideNav items={ categories } />

            {/* Center Browser */ }
            <section className="format-browser">
                <div className="search-container">
                    <div className="search-input-wrapper">
                        <Icon
                            src={ faMagnifyingGlassSolid }
                            className="icon"
                            size={ 16 }
                            color="var(--text-secondary)"
                        />
                        <input
                            type="text"
                            placeholder="Search for any format (e.g. PNG, MP4, WAV)..."
                            onInput={ (ev) => handleDebounceSearch(ev.currentTarget.value) }
                        />
                    </div>
                </div>

                <div className="format-list-container scroller">
                    <div className="list-header desktop-only">
                        {/* <h2>Common Formats</h2> */ }
                        <span>Showing { searchResultsIndex.size } formats</span>
                    </div>

                    <div className="format-grid">
                        {
                            Array.from(searchResultsIndex).map(([key, option]) => (
                                <FormatCard
                                    selected={ key === selectedOptionId }
                                    onSelect={ (key) => handleOptionSelection(key, option) }
                                    conversionOption={ option }
                                    id={ key }
                                    key={ key }
                                />
                            ))
                        }
                        {/* {
                            searchResultsIndex.map((option, i) => (
                                <FormatCard
                                    selected={ option[0] === selectedOptionId }
                                    onSelect={ (id) => handleFormatSelection(id, option) }
                                    formatType={ card }
                                    key={ card.id.concat(`-${i}`) }
                                    id={ card.id }
                                    handler={ card.handlerName }
                                />
                            ))
                        } */}
                    </div>
                </div>
            </section>
        </div>
    )
}
